const List<Map<String, String>> sleepTips = [
  // Alimentación
  {'category': 'Alimentación', 'tip': 'Evita la cafeína después de las 2pm. El café permanece en tu sistema hasta 8 horas.', 'icon': '☕'},
  {'category': 'Alimentación', 'tip': 'Una cena ligera 2-3 horas antes de dormir mejora la calidad del sueño.', 'icon': '🥗'},
  {'category': 'Alimentación', 'tip': 'El magnesio ayuda a relajar los músculos. Come almendras, espinaca o plátano antes de dormir.', 'icon': '🍌'},
  {'category': 'Alimentación', 'tip': 'El alcohol puede ayudarte a dormir más rápido pero fragmenta el sueño profundo.', 'icon': '🍷'},
  {'category': 'Alimentación', 'tip': 'Una taza de té de manzanilla puede reducir la ansiedad y prepararte para dormir.', 'icon': '🍵'},
  {'category': 'Alimentación', 'tip': 'Los alimentos ricos en triptófano (pavo, leche, huevos) favorecen la producción de melatonina.', 'icon': '🥚'},
  {'category': 'Alimentación', 'tip': 'Bebe suficiente agua durante el día, pero reduce la ingesta 1-2 horas antes de dormir.', 'icon': '💧'},
  {'category': 'Alimentación', 'tip': 'Los carbohidratos complejos como la avena pueden ayudar a conciliar el sueño más fácilmente.', 'icon': '🌾'},
  {'category': 'Alimentación', 'tip': 'Evita comidas muy condimentadas o ácidas en la cena para prevenir el reflujo nocturno.', 'icon': '🌶️'},
  {'category': 'Alimentación', 'tip': 'El kiwi contiene serotonina y antioxidantes. Comer uno antes de dormir puede mejorar el sueño.', 'icon': '🥝'},

  // Ejercicio
  {'category': 'Ejercicio', 'tip': '30 minutos de ejercicio aeróbico regular pueden mejorar la calidad del sueño hasta en un 65%.', 'icon': '🏃'},
  {'category': 'Ejercicio', 'tip': 'Evita el ejercicio intenso 3 horas antes de dormir. Eleva la temperatura corporal y energía.', 'icon': '⚡'},
  {'category': 'Ejercicio', 'tip': 'El yoga nocturno puede reducir la tensión muscular y preparar el cuerpo para el descanso.', 'icon': '🧘'},
  {'category': 'Ejercicio', 'tip': 'Una caminata suave después de cenar puede ayudar a la digestión y prepararte para dormir.', 'icon': '🚶'},
  {'category': 'Ejercicio', 'tip': 'El ejercicio regular regula el ritmo circadiano, haciendo que sea más fácil dormir a horarios fijos.', 'icon': '⏰'},
  {'category': 'Ejercicio', 'tip': 'Los ejercicios de estiramiento antes de dormir relajan los músculos y reducen los calambres nocturnos.', 'icon': '🤸'},
  {'category': 'Ejercicio', 'tip': 'Nadar o hacer ejercicio en agua reduce la temperatura corporal, facilitando el sueño.', 'icon': '🏊'},

  // Ambiente del cuarto
  {'category': 'Ambiente', 'tip': 'La temperatura ideal para dormir es entre 18-20°C. Un cuarto fresco favorece el sueño profundo.', 'icon': '🌡️'},
  {'category': 'Ambiente', 'tip': 'La oscuridad total suprime la melatonina. Usa cortinas blackout o un antifaz para dormir.', 'icon': '🌑'},
  {'category': 'Ambiente', 'tip': 'Los colores azules y grises en el dormitorio son más relajantes que los rojos o amarillos.', 'icon': '🎨'},
  {'category': 'Ambiente', 'tip': 'Un colchón de buena calidad puede mejorar el sueño un 60%. Reemplázalo cada 8-10 años.', 'icon': '🛏️'},
  {'category': 'Ambiente', 'tip': 'Las plantas como el aloe vera y la lavanda mejoran la calidad del aire y pueden reducir el estrés.', 'icon': '🌿'},
  {'category': 'Ambiente', 'tip': 'El sonido blanco o rosa puede enmascarar ruidos que interrumpen el sueño.', 'icon': '🔊'},
  {'category': 'Ambiente', 'tip': 'Mantén tu dormitorio solo para dormir. Trabajar en cama entrena al cerebro a no descansar allí.', 'icon': '🏠'},
  {'category': 'Ambiente', 'tip': 'La lavanda aromática puede reducir la frecuencia cardíaca y presión arterial, induciendo el sueño.', 'icon': '💜'},

  // Hábitos digitales
  {'category': 'Digital', 'tip': 'La luz azul de pantallas suprime la melatonina. Activa el modo noche 2 horas antes de dormir.', 'icon': '📱'},
  {'category': 'Digital', 'tip': 'Las redes sociales activan el cerebro con dopamina. Evítalas la última hora antes de dormir.', 'icon': '📲'},
  {'category': 'Digital', 'tip': 'Ver noticias antes de dormir puede aumentar la ansiedad. Desconéctate 1 hora antes.', 'icon': '📰'},
  {'category': 'Digital', 'tip': 'Los juegos de acción elevan el cortisol. Opta por juegos relajantes o libros en la noche.', 'icon': '🎮'},
  {'category': 'Digital', 'tip': 'Carga tu teléfono fuera del dormitorio para evitar la tentación de revisarlo de noche.', 'icon': '🔌'},
  {'category': 'Digital', 'tip': 'Las notificaciones nocturnas fragmentan el sueño REM. Activa el modo silencio al acostarte.', 'icon': '🔕'},
  {'category': 'Digital', 'tip': 'Los audiolibros o podcasts relajantes pueden ser una alternativa a las pantallas por la noche.', 'icon': '🎧'},

  // Rutinas de relajación
  {'category': 'Relajación', 'tip': 'La técnica 4-7-8: inhala 4 segundos, aguanta 7, exhala 8. Activa el sistema nervioso parasimpático.', 'icon': '🌬️'},
  {'category': 'Relajación', 'tip': 'Una rutina de sueño consistente ayuda al cerebro a anticipar el descanso y relajarse automáticamente.', 'icon': '📋'},
  {'category': 'Relajación', 'tip': 'Un baño caliente 1-2 horas antes de dormir baja la temperatura corporal al salir, induciendo el sueño.', 'icon': '🛁'},
  {'category': 'Relajación', 'tip': 'Leer un libro físico (no en pantalla) durante 6 minutos puede reducir el estrés en un 68%.', 'icon': '📚'},
  {'category': 'Relajación', 'tip': 'La relajación muscular progresiva: tensa y relaja cada grupo muscular de pies a cabeza.', 'icon': '💪'},
  {'category': 'Relajación', 'tip': 'Escribir un diario de gratitud antes de dormir puede reducir la preocupación y mejorar el sueño.', 'icon': '📔'},
  {'category': 'Relajación', 'tip': 'La visualización guiada de lugares tranquilos puede reducir la actividad mental nocturna.', 'icon': '🏖️'},
  {'category': 'Relajación', 'tip': 'La meditación mindfulness de 10 minutos antes de dormir reduce el insomnio crónico.', 'icon': '🧘'},

  // Estrés
  {'category': 'Estrés', 'tip': 'Haz una lista de tareas pendientes antes de dormir. "Descargar" la mente en papel ayuda a dormir.', 'icon': '📝'},
  {'category': 'Estrés', 'tip': 'El estrés eleva el cortisol, que inhibe la melatonina. Gestionar el estrés mejora directamente el sueño.', 'icon': '😤'},
  {'category': 'Estrés', 'tip': 'Si no puedes dormir después de 20 minutos, levántate y haz algo relajante. Vuelve cuando tengas sueño.', 'icon': '⏱️'},
  {'category': 'Estrés', 'tip': 'La técnica de "caja": inhala 4, aguanta 4, exhala 4, aguanta 4. Excelente para calmar la mente.', 'icon': '📦'},
  {'category': 'Estrés', 'tip': 'Hablar con alguien de tus preocupaciones antes de dormir puede liberar la carga mental.', 'icon': '💬'},
  {'category': 'Estrés', 'tip': 'Las preocupaciones nocturnas parecen más grandes en la oscuridad. Recuerda: mañana serán más manejables.', 'icon': '🌟'},
  {'category': 'Estrés', 'tip': 'Practica la autocompasión. Si no dormiste bien, no te culpes. El estrés por no dormir empeora el insomnio.', 'icon': '💕'},
  {'category': 'Estrés', 'tip': 'Los pensamientos negativos antes de dormir activan la amígdala. Enfócate en 3 cosas positivas del día.', 'icon': '✨'},
  {'category': 'Estrés', 'tip': 'La terapia cognitivo-conductual para el insomnio (TCC-I) es el tratamiento más efectivo a largo plazo.', 'icon': '🧠'},
  {'category': 'Estrés', 'tip': 'El ejercicio de respiración diafragmática activa el nervio vago y reduce la respuesta de estrés.', 'icon': '🫁'},
  {'category': 'Estrés', 'tip': 'La música a 60 BPM puede sincronizar las ondas cerebrales y facilitar la transición al sueño.', 'icon': '🎵'},
  {'category': 'Estrés', 'tip': 'Mantén un horario de sueño constante incluso los fines de semana. El "jet lag social" perjudica el descanso.', 'icon': '📅'},
];

const List<Map<String, dynamic>> habitProgram = [
  {'day': 1, 'title': 'Establece tu horario', 'desc': 'Define tu hora de dormir y despertar y configúralas en DreamTrack.', 'category': 'Base'},
  {'day': 2, 'title': 'Modo noche digital', 'desc': 'Activa el modo noche en todos tus dispositivos a partir de las 9pm.', 'category': 'Digital'},
  {'day': 3, 'title': 'Ritual de relajación', 'desc': 'Crea un ritual de 15 minutos antes de dormir (baño, lectura, estiramientos).', 'category': 'Relajación'},
  {'day': 4, 'title': 'Optimiza tu cuarto', 'desc': 'Ajusta la temperatura a 18-20°C y asegúrate de tener oscuridad total.', 'category': 'Ambiente'},
  {'day': 5, 'title': 'Elimina la cafeína tardía', 'desc': 'No consumas cafeína después de las 2pm por el resto del programa.', 'category': 'Alimentación'},
  {'day': 6, 'title': 'Ejercicio matutino', 'desc': 'Haz 30 minutos de ejercicio en la mañana para regular tu ritmo circadiano.', 'category': 'Ejercicio'},
  {'day': 7, 'title': 'Primera semana completada', 'desc': 'Revisa tus estadísticas. ¿Notas alguna mejora? Celebra tu progreso.', 'category': 'Reflexión'},
  {'day': 8, 'title': 'Diario de gratitud', 'desc': 'Escribe 3 cosas positivas del día antes de acostarte durante esta semana.', 'category': 'Estrés'},
  {'day': 9, 'title': 'Sin pantallas 1 hora antes', 'desc': 'Apaga todas las pantallas 1 hora antes de tu hora de dormir.', 'category': 'Digital'},
  {'day': 10, 'title': 'Técnica de respiración', 'desc': 'Practica la técnica 4-7-8 justo antes de dormir. 4 ciclos.', 'category': 'Relajación'},
  {'day': 11, 'title': 'Cena ligera', 'desc': 'Cena 2-3 horas antes de dormir. Nada pesado, nada muy picante.', 'category': 'Alimentación'},
  {'day': 12, 'title': 'Sonidos relajantes', 'desc': 'Usa los sonidos de DreamTrack por primera vez esta noche.', 'category': 'Ambiente'},
  {'day': 13, 'title': 'Sin alcohol', 'desc': 'Evita el alcohol esta noche y observa cómo afecta tu calidad de sueño.', 'category': 'Alimentación'},
  {'day': 14, 'title': 'Segunda semana completada', 'desc': 'Compara tus estadísticas con la primera semana. El cambio debería ser visible.', 'category': 'Reflexión'},
  {'day': 15, 'title': 'Relajación muscular progresiva', 'desc': 'Practica tensar y relajar cada músculo de pies a cabeza al acostarte.', 'category': 'Relajación'},
  {'day': 16, 'title': 'Optimiza el colchón y almohada', 'desc': 'Verifica que tu almohada soporte correctamente tu cuello y cabeza.', 'category': 'Ambiente'},
  {'day': 17, 'title': 'Lista de pendientes nocturna', 'desc': 'Escribe mañana por la mañana tus tareas del día siguiente esta noche.', 'category': 'Estrés'},
  {'day': 18, 'title': 'Yoga nocturno', 'desc': 'Haz 10-15 minutos de yoga suave o estiramientos antes de dormir.', 'category': 'Ejercicio'},
  {'day': 19, 'title': 'Hidratación inteligente', 'desc': 'Bebe suficiente agua antes de las 7pm y reduce líquidos después.', 'category': 'Alimentación'},
  {'day': 20, 'title': 'Chat con la IA', 'desc': 'Pregunta a la IA de DreamTrack qué aspectos de tu sueño puedes mejorar.', 'category': 'Reflexión'},
  {'day': 21, 'title': '¡Programa completado!', 'desc': '¡Felicidades! Has construido hábitos que mejorarán tu sueño de por vida.', 'category': 'Celebración'},
];
